services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hungph1996/pmo-assistant
    container_name: web-app
    ports:
      - 8000:8000
    volumes:
      - .:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: # key sẽ được tự động tạo
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: pmo_assistant
      DB_USERNAME: admin
      DB_PASSWORD: pmo123456
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pmo_assistant
      MYSQL_USER: admin
      MYSQL_PASSWORD: pmo123456
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
