version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: hungph1996/pmo-assistant
    container_name: web-app
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: # key sẽ được tự động tạo
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: pmo_assistant
      DB_USERNAME: admin
      DB_PASSWORD: pmo123456
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pmo_assistant
      MYSQL_USER: admin
      MYSQL_PASSWORD: pmo123456
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
